In [ ]:
def unique_elements(array):
    seen =[]
    unique=[]
    for num in array:
      if num not in seen:
        seen.append(num)
        unique.append(num)
    return unique
numbers=[1, 2, 2, 3, 4, 4, 4, 5, 6, 6, 7, 8, 9, 9]
print(unique_elements(numbers))

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
import numpy as np

class Matrix:
    def __init__(self, height, width):
        self.matrix = np.random.rand(height, width)

    def forward(self, vector):
        if self.matrix.shape[1] != len(vector):
            print("Error")

        else:
            result = np.dot(self.matrix, vector)
            return result

    def invert(self):
        if self.matrix.shape[0] != self.matrix.shape[1]:
            print("Matrix has to be a square one.")
            return None
        else:
            self.inverted_matrix = np.linalg.inv(self.matrix)
            return self.inverted_matrix

    def test(self):

        inverted_matrix = self.invert()

        identity_matrix = np.dot(self.matrix, inverted_matrix)
        if np.allclose(identity_matrix, np.eye(self.matrix.shape[0])):
            print("Test passed successfully")
        else:
            print("Test failed")


height = 3
width = 3

matrix = Matrix(height, width)

vector = np.array([1, 2, 3])

matrix = Matrix(height, width)
print(matrix.matrix)
print("result of multiplication:")
print(matrix.forward(vector))

matrix.test()








[[0.42162013 0.31630671 0.21892415]
 [0.05895457 0.08410366 0.46694113]
 [0.32910311 0.18045679 0.63219884]]
result of multiplication:
[1.711006   1.62798526 2.58661321]
Test passed successfully


In [5]:
import numpy as np

class ModifyMatrix:
    def __init__(self, a, sigma):
        self.a = a
        self.sigma = sigma

    def forward(self, x):

        mean_x = np.mean(x)
        std_x = np.std(x)

        x_standardized = (x - mean_x) / std_x

        x_modified = x_standardized * self.sigma + self.a

        return x_modified

def test_modify_matrix():

    a = 5
    sigma = 2
    modify_matrix = ModifyMatrix(a, sigma)

    x = np.random.rand(3, 3)

    x_modified = modify_matrix.forward(x)

    mean_modified = np.mean(x_modified)
    std_modified = np.std(x_modified)

    print(f"Original array:\n{x}")
    print(f"Modified array:\n{x_modified}")
    print(f"Expected mean: {a}, Calculated mean: {mean_modified}")
    print(f"Expected standard deviation: {sigma}, Calculated standard deviation: {std_modified}")

    assert np.isclose(mean_modified, a), f"Mean is incorrect: {mean_modified} != {a}"
    assert np.isclose(std_modified, sigma), f"Standard deviation is incorrect: {std_modified} != {sigma}"

    print("Test passed.")

test_modify_matrix()


Original array:
[[0.5246919  0.56558552 0.26617197]
 [0.92576023 0.45468595 0.26334547]
 [0.67050452 0.32126555 0.97667229]]
Modified array:
[[4.78097532 5.10805321 2.71326487]
 [7.98882532 4.22104934 2.69065782]
 [5.94722295 3.15391786 8.39603333]]
Expected mean: 5, Calculated mean: 5.000000000000002
Expected standard deviation: 2, Calculated standard deviation: 1.9999999999999996
Test passed.
