In [ ]:
def unique_elements(array):
    seen =[]
    unique=[]
    for num in array:
      if num not in seen:
        seen.append(num)
        unique.append(num)
    return unique
numbers=[1, 2, 2, 3, 4, 4, 4, 5, 6, 6, 7, 8, 9, 9]
print(unique_elements(numbers))

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [3]:
import numpy as np

class Matrix:
    def __init__(self, height, width):
        self.matrix = np.random.rand(height, width)

    def forward(self, vector):
        if self.matrix.shape[1] != len(vector):
            print("Error")

        else:
            result = np.dot(self.matrix, vector)
            return result

    def invert(self):
        if self.matrix.shape[0] != self.matrix.shape[1]:
            print("Matrix has to be a square one.")
            return None
        else:
            self.inverted_matrix = np.linalg.inv(self.matrix)
            return self.inverted_matrix

    def test(self):

        inverted_matrix = self.invert()

        identity_matrix = np.dot(self.matrix, inverted_matrix)
        if np.allclose(identity_matrix, np.eye(self.matrix.shape[0])):
            print("Test passed successfully")
        else:
            print("Test failed")


height = 3
width = 3

matrix = Matrix(height, width)

vector = np.array([1, 2, 3])

matrix = Matrix(height, width)
print(matrix.matrix)
print("result of multiplication:")
print(matrix.forward(vector))

matrix.test()








[[0.42162013 0.31630671 0.21892415]
 [0.05895457 0.08410366 0.46694113]
 [0.32910311 0.18045679 0.63219884]]
result of multiplication:
[1.711006   1.62798526 2.58661321]
Test passed successfully
